### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: unspentOutputs.map is not a function

### ISSUE THREAD

**Issue by GokulSreenivasa** [bigchaindb/project-jannowitz#1]
(node:5507) UnhandledPromiseRejectionWarning: TypeError: unspentOutputs.map is not a function
    at Object.makeTransferTransaction (/home/gokul/node_modules/bigchaindb-driver/dist/node/transaction/makeTransferTransaction.js:35:33)
    at transferAsset (/home/gokul/Documents/BigchainDB/role.js:244:43)
    at createUser (/home/gokul/Documents/BigchainDB/role.js:180:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
(node:5507) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:5507) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by manishverma01** [comment]
I am  getting the same issue
